services:
  flash-cards:
    build:
      context: .
      dockerfile: flash-cards.dockerfile
      args:
       VERSION: ${VERSION}
    ports:
      - 54789:54789
    volumes:
      - ./flash-cards/subjects/$SUBJECT:/root/.config/flash-cards-application
    env_file:
      - .env
    